### ISSUE TITLE
Partial image removal from S3

### ISSUE THREAD

**Issue by zvfvrv** [humanmade/S3-Uploads#196]
Hi!
i am using S3-Uploads-2.0.0-beta3, 
when deleting a media file, the originally uploaded file gets left behind - only the different thumbnail variants gets deleted from my S3 bucket!

Best regards

**Comment by pierventre** [comment]
Hi,
I am experiencing same issue on my EC2+S3 deployment.

Thanks
Pier

**Comment by tareq1988** [comment]
I'm using `v2.0.0`, but no media file is being deleted from S3 at all upon deleting from WordPress. 

That's a serious issue.

**Comment by alikuru** [comment]
Same here.

Using `v.2.0.0` with WordPress `v4.9.8`; when I try to delete a media file from the WordPress panel, although WordPress tells me it has been successfully deleted, it still can be found in the bucket. Result is the same with deleting one by one or in bulk mode.

This seems like a very useful setup and forget plugin, hope it gets fixed.

**Comment by jeremyfelt** [comment]
This was fixed previously in #92, but WP 4.9.7 broke that approach. Related core tickets: https://core.trac.wordpress.org/ticket/44563 and https://core.trac.wordpress.org/ticket/44706

**Comment by yemaw** [comment]
Any updates for this? All images original and thumbnail files not getting deleted.

I'm using S3-Upload v2.0.0 with wordpress v4.8.7.

**Comment by eightysixth** [comment]
Issue still present.
wp core version 5.0.3
S3-Upload 2.1 RC1

**Comment by nuvoPoint** [comment]
Same issue - all files stays in S3 after deleting them from WP.

Cloned this repo today and are using WP 5.1.1

**Comment by iamlili** [comment]
same problem on WP 5.1.1

**Comment by zeroiszero** [comment]
Hi, 
deleting a media file will deleted file in S3 bucket too when the right IAM policy given. I am using something like this:
```jsoon
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::YOUR_BUCKET_NAME/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

Noted: tried latest version of `s3-uploads` and `aws-php-sdk` as of now.

**Comment by VlasicVojislav** [comment]
Fixed by: https://github.com/humanmade/S3-Uploads/pull/307
