### ISSUE TITLE
Wordpress 4.9.6 and new GDPR Privacy Files problem

### ISSUE THREAD

**Issue by teolaz** [humanmade/S3-Uploads#242]
Hi there,
as this screenshot below:

![image](https://user-images.githubusercontent.com/19909323/40611004-e89571f4-6274-11e8-890a-d9d603c23c36.png)

I started to having problem in each site i mount S3-Uploads (20 sites circa)... Seems upload of each Privacy Files cannot be uploaded to S3 using the default WP method (please see wp-admin\includes\file.php, starting from row 1870).

Do you believe you can solve this?
Thanks

**Comment by teolaz** [comment]
FYI: inspected the code, and reported missing filters and action here: https://wordpress.org/support/topic/add-filters-to-wp_privacy_generate_personal_data_export_file-function/

**Comment by joehoyle** [comment]
Will have a look into this!

Envoyé de mon iPhone

**Comment by joehoyle** [comment]
@teolaz can you test the branch in https://github.com/humanmade/S3-Uploads/pull/243 which should fix this.

Thanks!

**Comment by teolaz** [comment]
@rmccue reopened because... ?

**Comment by rmccue** [comment]
@teolaz The issue is not actually fixed until the PR has been merged.
