### ISSUE TITLE
Attachment file deletion no longer works since WP version 4.9.7

### ISSUE THREAD

**Issue by l3rady** [humanmade/S3-Uploads#252]
https://core.trac.wordpress.org/ticket/44706#ticket

**Comment by pfiled** [comment]
Does anybody have any feedback on this? I've tested the patch in https://core.trac.wordpress.org/ticket/44563 but thumbnails are left in S3 after deletion.

**Comment by nhanledev** [comment]
Anyone has a fix? I'm new to this plugin and encountered the same error.

**Comment by nhanledev** [comment]
I have fixed this

First, apply this patch https://core.trac.wordpress.org/attachment/ticket/44563/wordpress-4.9.7-delete-media-streamwrapper.patch

Second, apply this patch https://github.com/nhanledev/S3-Uploads/commit/e19b75629d91113f41cf9ed2fed85ab8b8fb0dd3

**Comment by pfiled** [comment]
This was broken because of a change in core. I've been talking to core-media members who are interested in fixing it. It was going to be fixed in 4.9.9, but they changed the milestone just before @nhanledev shared his fix.

I have tested this fix extensively, and will comment to the same effect on ticket in wordpress.org. It would be nice if the fix were applied in both locations so I don't have to use composer-patches or forks to make it possible to fully delete media in our site.

**Comment by jay-oswald** [comment]
Still appears to be Broken on `5.0.3` Brand new site, brand new bucket, 1 file uploaded then deleted and its still in the bucket

**Comment by nhanledev** [comment]
Apply the patch from my previous reply. I still get it works on WP 5.0.3

**Comment by emanuelevannozzi** [comment]
I have the same issue, when i try to delete one image from wordpress media these not getting deleted , the only thing that the plugin remove is the link of the image in the wordpress DB, the images scaled and the original image remain in S3 space.
Please fix the error because the only thing that doesn't work correctly is this.
/***Informations/
Last wordpress update
last plugin update
Every Settings is in the right place

Is there any wat without overwrite functions.php wordpress core?

**Comment by jay-oswald** [comment]
@emanuelevannozzi nope, the issue is with core code, so to fix it have to override it... just means you have to keep doing it after every core WP update

**Comment by iamlili** [comment]
i'm having the same issue with wp 5.1.1
i've tested nhanledev's patches, which work, but prefer not to rely on this

Any idea if this will be fixed in future?

**Comment by rmccue** [comment]
cc @joemcgill for thoughts (if you have any)

**Comment by sirtawast** [comment]
Actually for those who don't want to wait, it's fixed in [2.1.0 RC2](https://github.com/humanmade/S3-Uploads/releases). I've tested this to be working ✔️ .

**Comment by sirtawast** [comment]
Related PR https://github.com/humanmade/S3-Uploads/pull/307
