### ISSUE TITLE
Warning: fwrite() expects parameter 1 to be resource, boolean given

### ISSUE THREAD

**Issue by mattpramschufer** [humanmade/S3-Uploads#331]
Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/wp-content/plugins/S3-Uploads/vendor/aws/aws-sdk-php/src/S3/Transfer.php on line 425

Latest version, the files are still uploaded just a ton of warnings

**Comment by thisboyiscrazy** [comment]
I am getting the same problem.

**Comment by thisboyiscrazy** [comment]
The problem is aws-sdk, Tansfer.php line 126 to 132 it expects $options['debug'] to true or unset.

Changing Lines 231 in class-s3-cli-command.php to
```
		$transfer_args = [
			'concurrency' => $args_assoc['concurrency'],
			'before'      => function ( AWS\Command $command ) {
				if ( in_array( $command->getName(), [ 'PutObject', 'CreateMultipartUpload' ], true ) ) {
					$acl = defined( 'S3_UPLOADS_OBJECT_ACL' ) ? S3_UPLOADS_OBJECT_ACL : 'public-read';
					$command['ACL'] = $acl;
				}
			},
		];

		if($args_assoc['verbose']) { $transfer_args['debug'] = true; };
```

Fixed it.

**Comment by AlanJIsaacson** [comment]
I have the same problem, but the fix above didn't resolve it

**Comment by ishigami** [comment]
For me the following command works for me:

`wp s3-uploads upload-directory /fullpath/to/uploads/ s3://uploads --verbose`

Just add the option `--verbose`
