### ISSUE TITLE
getid3 PHP 7.4 warnings

### ISSUE THREAD

**Issue by luishdz1010** [humanmade/S3-Uploads#369]
The current bundled version of getid3 is not fully compatible with PHP 7.4 . [Latests versions 1.9.18 and 1.9.19](https://github.com/JamesHeinrich/getID3/releases) contain the necessary fixes.

Warning output:
```
PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in ../s3-uploads/lib/getid3/getid3.php on line 554
PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in ../s3-uploads/lib/getid3/getid3.php on line 555
```

**Comment by aphoenix** [comment]
Is there any way to move this forward? It looks like the build failure is due to a recurring issue with tests, and not with the PR itself, and the linting errors are around a third party library that's being included.

Are these both barriers to getting this merged? Is there something someone else (like me?) could do to help push these along?

**Comment by carstenwawer** [comment]
Would be great to fix this.

**Comment by joehoyle** [comment]
Fixed in https://github.com/humanmade/S3-Uploads/pull/391

**Comment by turansadri** [comment]
I still get these error messages from the latest 2.2.2 release. Is this fix included in some release?
